services:
  frontend:
    ports:
      - "443:443"
    volumes:
      - ./deploy/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./deploy/certs/privkey.pem:/etc/nginx/certs/privkey.pem:ro
      - ./webApp/nginx/default.ssl.conf:/etc/nginx/conf.d/default.conf:ro
