#!/usr/bin/env bash
set -Eeuo pipefail

KEY_ID="${1:-${ALICIA_RS256_KEY_ID:-alicia-rs256-$(date -u +%Y%m%d%H%M%S)}}"
OUTPUT_DIR="${ALICIA_RS256_OUTPUT_DIR:-deploy/generated/identity-rs256}"
KEY_BITS="${ALICIA_RS256_KEY_BITS:-2048}"
ENV_FILE="${ALICIA_RS256_ENV_FILE:-.env}"

fail() {
    printf '[FAIL] %s\n' "$1" >&2
    exit 1
}

dotenv_value() {
    local key="$1"
    local line
    if [[ ! -f "$ENV_FILE" ]]; then
        return 0
    fi

    line="$(sed -n "s/^[[:space:]]*$key[[:space:]]*=[[:space:]]*//p" "$ENV_FILE" | tail -n 1)"
    line="${line%$'\r'}"
    line="${line%%#*}"
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"

    if [[ "${line:0:1}" == "\"" && "${line: -1}" == "\"" ]]; then
        line="${line:1:${#line}-2}"
    elif [[ "${line:0:1}" == "'" && "${line: -1}" == "'" ]]; then
        line="${line:1:${#line}-2}"
    fi

    printf '%s' "$line"
}

escape_pem_for_env() {
    awk 'BEGIN { ORS = "" } { sub(/\r$/, ""); printf "%s\\n", $0 }' "$1"
}

[[ "$KEY_ID" =~ ^[A-Za-z0-9._-]+$ ]] || fail "Key id may only contain letters, numbers, dot, underscore, or dash."
[[ "$KEY_BITS" =~ ^[0-9]+$ ]] || fail "RSA key bits must be a number."

command -v openssl >/dev/null 2>&1 || fail "openssl is required to generate RS256 keys."

umask 077
mkdir -p "$OUTPUT_DIR"

PRIVATE_KEY_FILE="$OUTPUT_DIR/$KEY_ID.private.pkcs8.pem"
PUBLIC_KEY_FILE="$OUTPUT_DIR/$KEY_ID.public.x509.pem"
ENV_SNIPPET_FILE="$OUTPUT_DIR/$KEY_ID.env"

for file in "$PRIVATE_KEY_FILE" "$PUBLIC_KEY_FILE" "$ENV_SNIPPET_FILE"; do
    if [[ -e "$file" ]]; then
        fail "$file already exists. Choose another key id or remove the old generated file intentionally."
    fi
done

openssl genpkey -algorithm RSA -pkeyopt "rsa_keygen_bits:$KEY_BITS" -out "$PRIVATE_KEY_FILE" >/dev/null 2>&1
openssl rsa -pubout -in "$PRIVATE_KEY_FILE" -out "$PUBLIC_KEY_FILE" >/dev/null 2>&1
chmod 600 "$PRIVATE_KEY_FILE"
chmod 600 "$PUBLIC_KEY_FILE"

CURRENT_HS256_KEY_ID="$(dotenv_value ALICIA_AUTH_TOKEN_KEY_ID)"
CURRENT_HS256_SECRET="$(dotenv_value ALICIA_AUTH_TOKEN_SECRET)"
CURRENT_PREVIOUS_KEYS="$(dotenv_value ALICIA_AUTH_TOKEN_PREVIOUS_KEYS)"

{
    printf '# Generated by deploy/scripts/generate-identity-rs256-env.sh\n'
    printf '# Copy these lines into .env, then rebuild the identity container.\n'
    printf 'ALICIA_AUTH_TOKEN_ALGORITHM=RS256\n'
    printf 'ALICIA_AUTH_TOKEN_KEY_ID=%s\n' "$KEY_ID"
    printf 'ALICIA_AUTH_TOKEN_RSA_PRIVATE_KEY=%s\n' "$(escape_pem_for_env "$PRIVATE_KEY_FILE")"
    printf 'ALICIA_AUTH_TOKEN_RSA_PUBLIC_KEY=%s\n' "$(escape_pem_for_env "$PUBLIC_KEY_FILE")"
    printf 'ALICIA_AUTH_TOKEN_PREVIOUS_RSA_PUBLIC_KEYS=%s\n' "$(dotenv_value ALICIA_AUTH_TOKEN_PREVIOUS_RSA_PUBLIC_KEYS)"
    if [[ -n "$CURRENT_HS256_KEY_ID" && -n "$CURRENT_HS256_SECRET" ]]; then
        if [[ -n "$CURRENT_PREVIOUS_KEYS" ]]; then
            printf 'ALICIA_AUTH_TOKEN_PREVIOUS_KEYS=%s=%s;%s\n' "$CURRENT_HS256_KEY_ID" "$CURRENT_HS256_SECRET" "$CURRENT_PREVIOUS_KEYS"
        else
            printf 'ALICIA_AUTH_TOKEN_PREVIOUS_KEYS=%s=%s\n' "$CURRENT_HS256_KEY_ID" "$CURRENT_HS256_SECRET"
        fi
    else
        printf '# ALICIA_AUTH_TOKEN_PREVIOUS_KEYS=alicia-hs256-v1=<current ALICIA_AUTH_TOKEN_SECRET>\n'
    fi
} > "$ENV_SNIPPET_FILE"
chmod 600 "$ENV_SNIPPET_FILE"

printf 'Generated RS256 identity key files:\n'
printf '  private key: %s\n' "$PRIVATE_KEY_FILE"
printf '  public key:  %s\n' "$PUBLIC_KEY_FILE"
printf '  env snippet: %s\n' "$ENV_SNIPPET_FILE"
printf '\nKeep these files private. They are under deploy/generated/, which is ignored by git.\n'
printf 'After copying the env snippet, rebuild identity, then run verify-identity-cloud-routes.sh.\n'
