package com.alicia.cloudstorage.identity.service;

public enum IdentityAuditEventType {
    LOGIN,
    TOKEN_REFRESH,
    LOGOUT,
    SESSION_REVOKE,
    PROFILE_UPDATE,
    PASSWORD_CHANGE,
    ADMIN_USER_CREATE,
    ADMIN_PASSWORD_RESET,
    ADMIN_APP_ROLE_UPDATE,
    EMAIL_REGISTRATION_CODE_REQUEST,
    EMAIL_REGISTRATION_VERIFY
}
