spring.application.name=identity-api
server.port=${SERVER_PORT:8082}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/alicia_cloud_storage?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
